project_identifier_env: CROWDIN_SITEMAKER_PROJECT_ID
api_key_env: CROWDIN_SITEMAKER_API_KEY
base_path: ./
preserve_hierarchy: true
files:
  -
    source: '/docs/docs/*.md'
    translation: '/docs/website/translated_docs/%locale%/%original_file_name%'
    languages_mapping: &anchor
      osx_locale:
        'zh-Hans': 'zh_cmn_hans'
        'zh-Hant': 'zh_cmn_hant'
  -
    source: '/docs/website/i18n/en.json'
    translation: '/docs/website/i18n/%locale%.json'
    languages_mapping: *anchor
  -
    source: '/docs/website/versioned_docs/**/*.md'
    translation: '/docs/website/translated_docs/%locale%/%original_file_name%'
    languages_mapping: *anchor
  -
    source: '/language/**/*.php'
    translation: '/language/%locale%/%original_file_name%'
    languages_mapping:
        'zh-Hans': 'zh_cmn_hans'
        'zh-Hant': 'zh_cmn_hant'
