project_identifier_env: CROWDIN_SITEMAKER_PROJECT_ID
api_key_env: CROWDIN_SITEMAKER_API_KEY
base_path: ./
preserve_hierarchy: true
files:
  -
    source: '/docs/docs/*.md'
    translation: '/docs/website/translated_docs/%two_letters_code%/%original_file_name%'
    languages_mapping:
      two_letters_code:
        'bs-BA': 'bs_ba'
        'pt-BR': 'pt_br'
        'zh-CN': 'zh_cmn_hans'
        'zh-TW': 'zh_cmn_hant'
  -
    source: '/docs/website/i18n/en.json'
    translation: '/docs/website/i18n/%two_letters_code%.json'
    languages_mapping:
      two_letters_code:
        'bs-BA': 'bs_ba'
        'pt-BR': 'pt_br'
        'zh-CN': 'zh_cmn_hans'
        'zh-TW': 'zh_cmn_hant'
  -
    source: '/docs/website/versioned_docs/**/*.md'
    translation: '/docs/website/translated_docs/%two_letters_code%/%original_file_name%'
    languages_mapping:
      two_letters_code:
        'bs-BA': 'bs_ba'
        'pt-BR': 'pt_br'
        'zh-CN': 'zh_cmn_hans'
        'zh-TW': 'zh_cmn_hant'
  -
    source: '/language/**/*.php'
    translation: '/language/%two_letters_code%/%original_file_name%'
    languages_mapping:
      two_letters_code:
        'bs-BA': 'bs_ba'
        'pt-BR': 'pt_br'
        'zh-CN': 'zh_cmn_hans'
        'zh-TW': 'zh_cmn_hant'
