project_identifier_env: CROWDIN_SITEMAKER_PROJECT_ID
api_key_env: CROWDIN_SITEMAKER_API_KEY
base_path: "./"
preserve_hierarchy: true
# commit_message: 'New translation for %original_file_name% in %language%'
# append_commit_message: false

files:
  -
    source: '/language/**/*.php'
    translation: '/language/%locale%/**/%original_file_name%'
    languages_mapping: &anchor
      locale:
        'bs-BA': 'bs_ba'
        'es-ES': 'es'
        'pt-BR': 'pt_preao'
        'pt-PT': 'pt'
        'sv-SE': 'sv'
        'zh-CN': 'zh_cmn_hans'
        'zh-TW': 'zh_cmn_hant'
