<?php

/**
 *
 * @package sitemaker
 * @copyright (c) 2015 Daniel A. (blitze)
 * @license http://opensource.org/licenses/gpl-2.0.php GNU General Public License v2
 *
 */

namespace blitze\sitemaker\tests\blocks;

use Symfony\Component\HttpFoundation\Request;
use blitze\sitemaker\model\mapper_factory;
use blitze\sitemaker\services\template;
use blitze\sitemaker\services\menus\display;
use blitze\sitemaker\services\menus\navigation;
use blitze\sitemaker\blocks\menu;

class menu_test extends blocks_base
{
	/**
	 * Load required fixtures.
	 *
	 * @return mixed
	 */
	public function getDataSet()
	{
		return $this->createXMLDataSet(dirname(__FILE__) . '/fixtures/menu.xml');
	}

	/**
	 * Create the menu block
	 *
	 * @param array $page_data
	 * @return \blitze\sitemaker\blocks\menu
	 */
	protected function get_block($page_data = array())
	{
		global $symfony_request;

		$symfony_request = new Request();

		$table_prefix = 'phpbb_';
		$tables = array(
			'mapper_tables'	=> array(
				'menus'	=> $table_prefix . 'sm_menus',
				'items'	=> $table_prefix . 'sm_menu_items'
			)
		);

		$this->user->host = 'www.example.com';
		$this->user->page = $page_data;
		$this->user->page['root_script_path'] = '/phpBB/';
		$this->user->style = array(
			'style_name' => 'all',
			'style_path' => 'all',
		);

		$mapper_factory = new mapper_factory($this->config, $this->db, $tables);

		$tree = new display($this->db, $this->user, $tables['mapper_tables']['items'], 'item_id');

		$navigation = new navigation($this->cache, $mapper_factory, $tree, $this->php_ext);

		return new menu($this->translator, $navigation);
	}

	public function test_block_config()
	{
		$block = $this->get_block();
		$config = $block->get_config(array());

		$expected_keys = array(
			'legend1',
			'menu_id',
			'expanded',
			'max_depth',
		);

		$this->assertEquals($expected_keys, array_keys($config));
	}

	/**
	 * Data set for test_menu_block_display
	 *
	 * @return array
	 */
	public function menu_block_test_data()
	{
		return array(
			array(
				array(),
				array(
					'settings' => array(
						'menu_id' => 0,
						'expanded' => 0,
						'max_depth' => 3,
					),
				),
				false,
				'',
			),
			array(
				array(),
				array(
					'settings' => array(
						'menu_id' => 0,
						'expanded' => 0,
						'max_depth' => 3,
					),
				),
				true,
				'SELECT_MENU',
			),
			array(
				array(),
				array(
					'settings' => array(
						'menu_id' => 2,
						'expanded' => 0,
						'max_depth' => 3,
					),
				),
				false,
				'',
			),
			array(
				array(),
				array(
					'settings' => array(
						'menu_id' => 2,
						'expanded' => 0,
						'max_depth' => 3,
					),
				),
				true,
				'MENU_NO_ITEMS',
			),
			array(
				array(
					'page_name' => 'faq.php',
					'page_dir' => '',
					'query_string' => '',
				),
				array(
					'settings' => array(
						'menu_id' => 1,
						'expanded' => 0,
						'max_depth' => 3,
					),
				),
				false,
				array(
					'tree' => array(
						array(
							'ITEM_ID' => 1,
							'MENU_ID' => 1,
							'PARENT_ID' => 0,
							'ITEM_TITLE' => 'Home',
							'ITEM_URL' => '/index.php',
							'ITEM_ICON' => 'fa fa-home ',
							'ITEM_TARGET' => 0,
							'LEFT_ID' => 1,
							'RIGHT_ID' => 2,
							'ITEM_PARENTS' => '',
							'DEPTH' => 0,
							'FULL_URL' => 'http://www.example.com/phpBB/index.php',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '/',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => true,
							'IS_EXPANDABLE' => true,
							'PREV_DEPTH' => 0,
							'THIS_DEPTH' => 0,
							'IS_CURRENT' => false,
							'IS_PARENT' => false,
							'NUM_KIDS' => 0,
							'close' => [],
						),
						array(
							'ITEM_ID' => 2,
							'MENU_ID' => 1,
							'PARENT_ID' => 0,
							'ITEM_TITLE' => 'Content',
							'ITEM_URL' => '/app.php/page/content/',
							'ITEM_ICON' => '',
							'ITEM_TARGET' => 0,
							'LEFT_ID' => 3,
							'RIGHT_ID' => 4,
							'ITEM_PARENTS' => '',
							'DEPTH' => 0,
							'FULL_URL' => 'http://www.example.com/phpBB/app.php/page/content/',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '/app.php/page/content/',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => true,
							'IS_EXPANDABLE' => true,
							'PREV_DEPTH' => 0,
							'THIS_DEPTH' => 0,
							'IS_CURRENT' => false,
							'IS_PARENT' => false,
							'NUM_KIDS' => 0,
							'close' => [],
						),
						array(
							'ITEM_ID' => 8,
							'MENU_ID' => 1,
							'PARENT_ID' => 0,
							'ITEM_TITLE' => 'About Us',
							'ITEM_URL' => '/app.php/page/about',
							'ITEM_ICON' => '',
							'ITEM_TARGET' => 0,
							'LEFT_ID' => 15,
							'RIGHT_ID' => 16,
							'ITEM_PARENTS' => '',
							'DEPTH' => 0,
							'FULL_URL' => 'http://www.example.com/phpBB/app.php/page/about',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '/app.php/page/about',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => true,
							'IS_EXPANDABLE' => true,
							'PREV_DEPTH' => 0,
							'THIS_DEPTH' => 0,
							'IS_CURRENT' => false,
							'IS_PARENT' => false,
							'NUM_KIDS' => 0,
							'close' => [],
						),
					),
					'close' => [],
				),
			),
			array(
				array(
					'page_name' => 'index.php',
					'page_dir' => '',
					'query_string' => '',
				),
				array(
					'settings' => array(
						'menu_id' => 1,
						'expanded' => 0,
						'max_depth' => 3,
					),
				),
				false,
				array(
					'tree' => array(
						array(
							'ITEM_ID' => 1,
							'MENU_ID' => 1,
							'PARENT_ID' => 0,
							'ITEM_TITLE' => 'Home',
							'ITEM_URL' => '/index.php',
							'ITEM_ICON' => 'fa fa-home ',
							'ITEM_TARGET' => 0,
							'LEFT_ID' => 1,
							'RIGHT_ID' => 2,
							'ITEM_PARENTS' => '',
							'DEPTH' => 0,
							'FULL_URL' => 'http://www.example.com/phpBB/index.php',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '/',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => true,
							'IS_EXPANDABLE' => true,
							'PREV_DEPTH' => 0,
							'THIS_DEPTH' => 0,
							'IS_CURRENT' => true,
							'IS_PARENT' => false,
							'NUM_KIDS' => 0,
							'close' => [],
						),
						array(
							'ITEM_ID' => 2,
							'MENU_ID' => 1,
							'PARENT_ID' => 0,
							'ITEM_TITLE' => 'Content',
							'ITEM_URL' => '/app.php/page/content/',
							'ITEM_ICON' => '',
							'ITEM_TARGET' => 0,
							'LEFT_ID' => 3,
							'RIGHT_ID' => 4,
							'ITEM_PARENTS' => '',
							'DEPTH' => 0,
							'FULL_URL' => 'http://www.example.com/phpBB/app.php/page/content/',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '/app.php/page/content/',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => true,
							'IS_EXPANDABLE' => true,
							'PREV_DEPTH' => 0,
							'THIS_DEPTH' => 0,
							'IS_CURRENT' => false,
							'IS_PARENT' => false,
							'NUM_KIDS' => 0,
							'close' => [],
						),
						array(
							'ITEM_ID' => 8,
							'MENU_ID' => 1,
							'PARENT_ID' => 0,
							'ITEM_TITLE' => 'About Us',
							'ITEM_URL' => '/app.php/page/about',
							'ITEM_ICON' => '',
							'ITEM_TARGET' => 0,
							'LEFT_ID' => 15,
							'RIGHT_ID' => 16,
							'ITEM_PARENTS' => '',
							'DEPTH' => 0,
							'FULL_URL' => 'http://www.example.com/phpBB/app.php/page/about',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '/app.php/page/about',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => true,
							'IS_EXPANDABLE' => true,
							'PREV_DEPTH' => 0,
							'THIS_DEPTH' => 0,
							'IS_CURRENT' => false,
							'IS_PARENT' => false,
							'NUM_KIDS' => 0,
							'close' => [],
						),
					),
					'close' => [],
				),
			),
			array(
				array(
					'page_name' => 'app.php/page/USA',
					'page_dir' => '',
					'query_string' => '',
				),
				array(
					'settings' => array(
						'menu_id' => 1,
						'expanded' => 0,
						'max_depth' => 3,
					),
				),
				false,
				array(
					'tree' => array(
						array(
							'ITEM_ID' => 1,
							'MENU_ID' => 1,
							'PARENT_ID' => 0,
							'ITEM_TITLE' => 'Home',
							'ITEM_URL' => '/index.php',
							'ITEM_ICON' => 'fa fa-home ',
							'ITEM_TARGET' => 0,
							'LEFT_ID' => 1,
							'RIGHT_ID' => 2,
							'ITEM_PARENTS' => '',
							'DEPTH' => 0,
							'FULL_URL' => 'http://www.example.com/phpBB/index.php',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '/',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => true,
							'IS_EXPANDABLE' => true,
							'PREV_DEPTH' => 0,
							'THIS_DEPTH' => 0,
							'IS_CURRENT' => false,
							'IS_PARENT' => false,
							'NUM_KIDS' => 0,
							'close' => [],
						),
						array(
							'ITEM_ID' => 2,
							'MENU_ID' => 1,
							'PARENT_ID' => 0,
							'ITEM_TITLE' => 'Content',
							'ITEM_URL' => '/app.php/page/content/',
							'ITEM_ICON' => '',
							'ITEM_TARGET' => 0,
							'LEFT_ID' => 3,
							'RIGHT_ID' => 14,
							'ITEM_PARENTS' => '',
							'DEPTH' => 0,
							'FULL_URL' => 'http://www.example.com/phpBB/app.php/page/content/',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '/app.php/page/content/',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => true,
							'IS_EXPANDABLE' => true,
							'PREV_DEPTH' => 0,
							'THIS_DEPTH' => 0,
							'IS_CURRENT' => false,
							'IS_PARENT' => true,
							'NUM_KIDS' => 5,
							'close' => [],
						),
						array(
							'ITEM_ID' => 3,
							'MENU_ID' => 1,
							'PARENT_ID' => 2,
							'ITEM_TITLE' => 'News',
							'ITEM_URL' => '/app.php/page/news',
							'ITEM_ICON' => '',
							'ITEM_TARGET' => 0,
							'LEFT_ID' => 4,
							'RIGHT_ID' => 11,
							'ITEM_PARENTS' => '',
							'DEPTH' => 1,
							'FULL_URL' => 'http://www.example.com/phpBB/app.php/page/news',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '/app.php/page/news',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => true,
							'IS_EXPANDABLE' => true,
							'PREV_DEPTH' => 0,
							'THIS_DEPTH' => 1,
							'IS_CURRENT' => false,
							'IS_PARENT' => true,
							'NUM_KIDS' => 3,
							'close' => [''],
						),
						array(
							'ITEM_ID' => 4,
							'MENU_ID' => 1,
							'PARENT_ID' => 3,
							'ITEM_TITLE' => 'USA',
							'ITEM_URL' => '/app.php/page/USA',
							'ITEM_ICON' => '',
							'ITEM_TARGET' => 0,
							'LEFT_ID' => 5,
							'RIGHT_ID' => 10,
							'ITEM_PARENTS' => '',
							'DEPTH' => 2,
							'FULL_URL' => 'http://www.example.com/phpBB/app.php/page/USA',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '/app.php/page/USA',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => true,
							'IS_EXPANDABLE' => true,
							'PREV_DEPTH' => 1,
							'THIS_DEPTH' => 2,
							'IS_CURRENT' => true,
							'IS_PARENT' => false,
							'NUM_KIDS' => 2,
							'close' => [''],
						),
						array(
							'ITEM_ID' => 5,
							'MENU_ID' => 1,
							'PARENT_ID' => 4,
							'ITEM_TITLE' => 'Business',
							'ITEM_URL' => '/viewtopic.php?f=1&t=2',
							'ITEM_ICON' => '',
							'ITEM_TARGET' => 0,
							'LEFT_ID' => 6,
							'RIGHT_ID' => 7,
							'ITEM_PARENTS' => '',
							'DEPTH' => 3,
							'FULL_URL' => 'http://www.example.com/phpBB/viewtopic.php?f=1&t=2',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '/viewtopic.php',
							'URL_QUERY' => ['f=1', 't=2'],
							'IS_NAVIGABLE' => true,
							'IS_EXPANDABLE' => true,
							'PREV_DEPTH' => 2,
							'THIS_DEPTH' => 3,
							'IS_CURRENT' => false,
							'IS_PARENT' => false,
							'NUM_KIDS' => 0,
							'close' => [''],
						),
						array(
							'ITEM_ID' => 7,
							'MENU_ID' => 1,
							'PARENT_ID' => 2,
							'ITEM_TITLE' => 'Articles',
							'ITEM_URL' => '/app.php/content/articles',
							'ITEM_ICON' => '',
							'ITEM_TARGET' => 1,
							'LEFT_ID' => 12,
							'RIGHT_ID' => 13,
							'ITEM_PARENTS' => '',
							'DEPTH' => 1,
							'FULL_URL' => 'http://www.example.com/phpBB/app.php/content/articles',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '/app.php/content/articles',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => true,
							'IS_EXPANDABLE' => false,
							'PREV_DEPTH' => 3,
							'THIS_DEPTH' => 1,
							'IS_CURRENT' => false,
							'IS_PARENT' => false,
							'NUM_KIDS' => 0,
							'close' => ['', ''],
						),
						array(
							'ITEM_ID' => 8,
							'MENU_ID' => 1,
							'PARENT_ID' => 0,
							'ITEM_TITLE' => 'About Us',
							'ITEM_URL' => '/app.php/page/about',
							'ITEM_ICON' => '',
							'ITEM_TARGET' => 0,
							'LEFT_ID' => 15,
							'RIGHT_ID' => 16,
							'ITEM_PARENTS' => '',
							'DEPTH' => 0,
							'FULL_URL' => 'http://www.example.com/phpBB/app.php/page/about',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '/app.php/page/about',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => true,
							'IS_EXPANDABLE' => true,
							'PREV_DEPTH' => 1,
							'THIS_DEPTH' => 0,
							'IS_CURRENT' => false,
							'IS_PARENT' => false,
							'NUM_KIDS' => 0,
							'close' => [''],
						),
					),
					'close' => [],
				),
			),
			array(
				array(
					'page_name' => 'viewtopic.php',
					'page_dir' => '',
					'query_string' => 'f=1&t=2',
				),
				array(
					'settings' => array(
						'menu_id' => 1,
						'expanded' => 0,
						'max_depth' => 3,
					),
				),
				false,
				array(
					'tree' => array(
						array(
							'ITEM_ID' => 3,
							'MENU_ID' => 1,
							'PARENT_ID' => 2,
							'ITEM_TITLE' => 'News',
							'ITEM_URL' => '/app.php/page/news',
							'ITEM_ICON' => '',
							'ITEM_TARGET' => 0,
							'LEFT_ID' => 4,
							'RIGHT_ID' => 11,
							'ITEM_PARENTS' => '',
							'DEPTH' => 1,
							'FULL_URL' => 'http://www.example.com/phpBB/app.php/page/news',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '/app.php/page/news',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => true,
							'IS_EXPANDABLE' => true,
							'PREV_DEPTH' => 1,
							'THIS_DEPTH' => 1,
							'IS_CURRENT' => false,
							'IS_PARENT' => true,
							'NUM_KIDS' => 3,
							'close' => [],
						),
						1 =>
						array(
							'ITEM_ID' => 4,
							'MENU_ID' => 1,
							'PARENT_ID' => 3,
							'ITEM_TITLE' => 'USA',
							'ITEM_URL' => '/app.php/page/USA',
							'ITEM_ICON' => '',
							'ITEM_TARGET' => 0,
							'LEFT_ID' => 5,
							'RIGHT_ID' => 10,
							'ITEM_PARENTS' => '',
							'DEPTH' => 2,
							'FULL_URL' => 'http://www.example.com/phpBB/app.php/page/USA',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '/app.php/page/USA',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => true,
							'IS_EXPANDABLE' => true,
							'PREV_DEPTH' => 1,
							'THIS_DEPTH' => 2,
							'IS_CURRENT' => false,
							'IS_PARENT' => true,
							'NUM_KIDS' => 2,
							'close' => [''],
						),
						array(
							'ITEM_ID' => 5,
							'MENU_ID' => 1,
							'PARENT_ID' => 4,
							'ITEM_TITLE' => 'Business',
							'ITEM_URL' => '/viewtopic.php?f=1&t=2',
							'ITEM_ICON' => '',
							'ITEM_TARGET' => 0,
							'LEFT_ID' => 6,
							'RIGHT_ID' => 9,
							'ITEM_PARENTS' => '',
							'DEPTH' => 3,
							'FULL_URL' => 'http://www.example.com/phpBB/viewtopic.php?f=1&t=2',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '/viewtopic.php',
							'URL_QUERY' => ['f=1', 't=2'],
							'IS_NAVIGABLE' => true,
							'IS_EXPANDABLE' => true,
							'PREV_DEPTH' => 2,
							'THIS_DEPTH' => 3,
							'IS_CURRENT' => true,
							'IS_PARENT' => false,
							'NUM_KIDS' => 1,
							'close' => [''],
						),
						array(
							'ITEM_ID' => 6,
							'MENU_ID' => 1,
							'PARENT_ID' => 5,
							'ITEM_TITLE' => 'Startups',
							'ITEM_URL' => '/app.php/page/startups',
							'ITEM_ICON' => '',
							'ITEM_TARGET' => 0,
							'LEFT_ID' => 7,
							'RIGHT_ID' => 8,
							'ITEM_PARENTS' => '',
							'DEPTH' => 4,
							'FULL_URL' => 'http://www.example.com/phpBB/app.php/page/startups',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '/app.php/page/startups',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => true,
							'IS_EXPANDABLE' => true,
							'PREV_DEPTH' => 3,
							'THIS_DEPTH' => 4,
							'IS_CURRENT' => false,
							'IS_PARENT' => false,
							'NUM_KIDS' => 0,
							'close' => [''],
						),
						array(
							'ITEM_ID' => 7,
							'MENU_ID' => 1,
							'PARENT_ID' => 2,
							'ITEM_TITLE' => 'Articles',
							'ITEM_URL' => '/app.php/content/articles',
							'ITEM_ICON' => '',
							'ITEM_TARGET' => 1,
							'LEFT_ID' => 12,
							'RIGHT_ID' => 13,
							'ITEM_PARENTS' => '',
							'DEPTH' => 1,
							'FULL_URL' => 'http://www.example.com/phpBB/app.php/content/articles',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '/app.php/content/articles',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => true,
							'IS_EXPANDABLE' => false,
							'PREV_DEPTH' => 4,
							'THIS_DEPTH' => 1,
							'IS_CURRENT' => false,
							'IS_PARENT' => false,
							'NUM_KIDS' => 0,
							'close' => ['', '', ''],
						),
					),
					'close' => [],
				),
			),
			array(
				array(
					'page_name' => 'index.php',
					'page_dir' => '',
					'query_string' => '',
				),
				array(
					'settings' => array(
						'menu_id' => 1,
						'expanded' => 1,
						'max_depth' => 3,
					),
				),
				false,
				array(
					'tree' => array(
						array(
							'ITEM_ID' => 1,
							'MENU_ID' => 1,
							'PARENT_ID' => 0,
							'ITEM_TITLE' => 'Home',
							'ITEM_URL' => '/index.php',
							'ITEM_ICON' => 'fa fa-home ',
							'ITEM_TARGET' => 0,
							'LEFT_ID' => 1,
							'RIGHT_ID' => 2,
							'ITEM_PARENTS' => '',
							'DEPTH' => 0,
							'FULL_URL' => 'http://www.example.com/phpBB/index.php',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '/',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => true,
							'IS_EXPANDABLE' => true,
							'PREV_DEPTH' => 0,
							'THIS_DEPTH' => 0,
							'IS_CURRENT' => true,
							'IS_PARENT' => false,
							'NUM_KIDS' => 0,
							'close' => [],
						),
						array(
							'ITEM_ID' => 2,
							'MENU_ID' => 1,
							'PARENT_ID' => 0,
							'ITEM_TITLE' => 'Content',
							'ITEM_URL' => '/app.php/page/content/',
							'ITEM_ICON' => '',
							'ITEM_TARGET' => 0,
							'LEFT_ID' => 3,
							'RIGHT_ID' => 14,
							'ITEM_PARENTS' => '',
							'DEPTH' => 0,
							'FULL_URL' => 'http://www.example.com/phpBB/app.php/page/content/',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '/app.php/page/content/',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => true,
							'IS_EXPANDABLE' => true,
							'PREV_DEPTH' => 0,
							'THIS_DEPTH' => 0,
							'IS_CURRENT' => false,
							'IS_PARENT' => false,
							'NUM_KIDS' => 5,
							'close' => [],
						),
						array(
							'ITEM_ID' => 3,
							'MENU_ID' => 1,
							'PARENT_ID' => 2,
							'ITEM_TITLE' => 'News',
							'ITEM_URL' => '/app.php/page/news',
							'ITEM_ICON' => '',
							'ITEM_TARGET' => 0,
							'LEFT_ID' => 4,
							'RIGHT_ID' => 11,
							'ITEM_PARENTS' => '',
							'DEPTH' => 1,
							'FULL_URL' => 'http://www.example.com/phpBB/app.php/page/news',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '/app.php/page/news',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => true,
							'IS_EXPANDABLE' => true,
							'PREV_DEPTH' => 0,
							'THIS_DEPTH' => 1,
							'IS_CURRENT' => false,
							'IS_PARENT' => false,
							'NUM_KIDS' => 3,
							'close' => [''],
						),
						array(
							'ITEM_ID' => 4,
							'MENU_ID' => 1,
							'PARENT_ID' => 3,
							'ITEM_TITLE' => 'USA',
							'ITEM_URL' => '/app.php/page/USA',
							'ITEM_ICON' => '',
							'ITEM_TARGET' => 0,
							'LEFT_ID' => 5,
							'RIGHT_ID' => 10,
							'ITEM_PARENTS' => '',
							'DEPTH' => 2,
							'FULL_URL' => 'http://www.example.com/phpBB/app.php/page/USA',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '/app.php/page/USA',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => true,
							'IS_EXPANDABLE' => true,
							'PREV_DEPTH' => 1,
							'THIS_DEPTH' => 2,
							'IS_CURRENT' => false,
							'IS_PARENT' => false,
							'NUM_KIDS' => 2,
							'close' => [''],
						),
						array(
							'ITEM_ID' => 5,
							'MENU_ID' => 1,
							'PARENT_ID' => 4,
							'ITEM_TITLE' => 'Business',
							'ITEM_URL' => '/viewtopic.php?f=1&t=2',
							'ITEM_ICON' => '',
							'ITEM_TARGET' => 0,
							'LEFT_ID' => 6,
							'RIGHT_ID' => 7,
							'ITEM_PARENTS' => '',
							'DEPTH' => 3,
							'FULL_URL' => 'http://www.example.com/phpBB/viewtopic.php?f=1&t=2',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '/viewtopic.php',
							'URL_QUERY' => ['f=1', 't=2'],
							'IS_NAVIGABLE' => true,
							'IS_EXPANDABLE' => true,
							'PREV_DEPTH' => 2,
							'THIS_DEPTH' => 3,
							'IS_CURRENT' => false,
							'IS_PARENT' => false,
							'NUM_KIDS' => 0,
							'close' => [''],
						),
						array(
							'ITEM_ID' => 7,
							'MENU_ID' => 1,
							'PARENT_ID' => 2,
							'ITEM_TITLE' => 'Articles',
							'ITEM_URL' => '/app.php/content/articles',
							'ITEM_ICON' => '',
							'ITEM_TARGET' => 1,
							'LEFT_ID' => 12,
							'RIGHT_ID' => 13,
							'ITEM_PARENTS' => '',
							'DEPTH' => 1,
							'FULL_URL' => 'http://www.example.com/phpBB/app.php/content/articles',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '/app.php/content/articles',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => true,
							'IS_EXPANDABLE' => false,
							'PREV_DEPTH' => 3,
							'THIS_DEPTH' => 1,
							'IS_CURRENT' => false,
							'IS_PARENT' => false,
							'NUM_KIDS' => 0,
							'close' => ['', ''],
						),
						array(
							'ITEM_ID' => 8,
							'MENU_ID' => 1,
							'PARENT_ID' => 0,
							'ITEM_TITLE' => 'About Us',
							'ITEM_URL' => '/app.php/page/about',
							'ITEM_ICON' => '',
							'ITEM_TARGET' => 0,
							'LEFT_ID' => 15,
							'RIGHT_ID' => 16,
							'ITEM_PARENTS' => '',
							'DEPTH' => 0,
							'FULL_URL' => 'http://www.example.com/phpBB/app.php/page/about',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '/app.php/page/about',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => true,
							'IS_EXPANDABLE' => true,
							'PREV_DEPTH' => 1,
							'THIS_DEPTH' => 0,
							'IS_CURRENT' => false,
							'IS_PARENT' => false,
							'NUM_KIDS' => 0,
							'close' => [''],
						),
					),
					'close' => [],
				),
			),
			array(
				array(
					'page_name' => 'index.php',
					'page_dir' => '',
					'query_string' => '',
				),
				array(
					'settings' => array(
						'menu_id' => 4,
						'expanded' => 0,
						'max_depth' => 3,
					),
				),
				false,
				array(
					'tree' => array(
						array(
							'ITEM_ID' => 13,
							'MENU_ID' => 4,
							'PARENT_ID' => 0,
							'ITEM_TITLE' => 'Item 1',
							'ITEM_URL' => 'http://www.google.com',
							'ITEM_ICON' => '',
							'ITEM_TARGET' => 0,
							'LEFT_ID' => 1,
							'RIGHT_ID' => 4,
							'ITEM_PARENTS' => '',
							'DEPTH' => 0,
							'FULL_URL' => 'http://www.google.com',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => 'www.google.com',
							'URL_PATH' => '',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => false,
							'IS_EXPANDABLE' => false,
							'PREV_DEPTH' => 0,
							'THIS_DEPTH' => 0,
							'IS_CURRENT' => false,
							'IS_PARENT' => false,
							'NUM_KIDS' => 1,
							'close' => [],
						),
						array(
							'ITEM_ID' => 14,
							'MENU_ID' => 4,
							'PARENT_ID' => 13,
							'ITEM_TITLE' => 'Item 2',
							'ITEM_URL' => '#',
							'ITEM_ICON' => '',
							'ITEM_TARGET' => 0,
							'LEFT_ID' => 2,
							'RIGHT_ID' => 3,
							'ITEM_PARENTS' => '',
							'DEPTH' => 1,
							'FULL_URL' => '#',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => false,
							'IS_EXPANDABLE' => false,
							'PREV_DEPTH' => 0,
							'THIS_DEPTH' => 1,
							'IS_CURRENT' => false,
							'IS_PARENT' => false,
							'NUM_KIDS' => 0,
							'close' => [''],
						),
					),
					'close' => [''],
				),
			),
			array(
				array(
					'page_name' => 'index.php',
					'page_dir' => '',
					'query_string' => '',
				),
				array(
					'settings' => array(
						'menu_id' => 5,
						'expanded' => 0,
						'max_depth' => 3,
					),
				),
				false,
				array(
					'tree' => array(
						array(
							'ITEM_ID' => 15,
							'MENU_ID' => 5,
							'PARENT_ID' => 0,
							'ITEM_TITLE' => 'Item 1',
							'ITEM_URL' => '/faq.php',
							'ITEM_ICON' => '',
							'ITEM_TARGET' => 1,
							'LEFT_ID' => 1,
							'RIGHT_ID' => 4,
							'ITEM_PARENTS' => '',
							'DEPTH' => 0,
							'FULL_URL' => 'http://www.example.com/phpBB/faq.php',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '/faq.php',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => true,
							'IS_EXPANDABLE' => false,
							'PREV_DEPTH' => 0,
							'THIS_DEPTH' => 0,
							'IS_CURRENT' => false,
							'IS_PARENT' => false,
							'NUM_KIDS' => 1,
							'close' => [],
						),
						array(
							'ITEM_ID' => 16,
							'MENU_ID' => 5,
							'PARENT_ID' => 15,
							'ITEM_TITLE' => 'Item 2',
							'ITEM_URL' => '#',
							'ITEM_ICON' => '',
							'ITEM_TARGET' => 0,
							'LEFT_ID' => 2,
							'RIGHT_ID' => 3,
							'ITEM_PARENTS' => '',
							'DEPTH' => 1,
							'FULL_URL' => '#',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => false,
							'IS_EXPANDABLE' => false,
							'PREV_DEPTH' => 0,
							'THIS_DEPTH' => 1,
							'IS_CURRENT' => false,
							'IS_PARENT' => false,
							'NUM_KIDS' => 0,
							'close' => [''],
						),
					),
					'close' => [''],
				),
			),
			array(
				array(
					'page_name' => 'index.php',
					'page_dir' => '',
					'query_string' => '',
				),
				array(
					'settings' => array(
						'menu_id' => 6,
						'expanded' => 0,
						'max_depth' => 3,
					),
				),
				false,
				array(
					'tree' => array(
						array(
							'ITEM_ID' => 17,
							'MENU_ID' => 6,
							'PARENT_ID' => 0,
							'ITEM_TITLE' => 'Item 1',
							'ITEM_URL' => '/file.zip',
							'ITEM_ICON' => '',
							'ITEM_TARGET' => 0,
							'LEFT_ID' => 1,
							'RIGHT_ID' => 4,
							'ITEM_PARENTS' => '',
							'DEPTH' => 0,
							'FULL_URL' => 'http://www.example.com/phpBB/file.zip',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '/file.zip',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => false,
							'IS_EXPANDABLE' => false,
							'PREV_DEPTH' => 0,
							'THIS_DEPTH' => 0,
							'IS_CURRENT' => false,
							'IS_PARENT' => false,
							'NUM_KIDS' => 1,
							'close' => [],
						),
						array(
							'ITEM_ID' => 18,
							'MENU_ID' => 6,
							'PARENT_ID' => 17,
							'ITEM_TITLE' => 'Item 2',
							'ITEM_URL' => '#',
							'ITEM_ICON' => '',
							'ITEM_TARGET' => 0,
							'LEFT_ID' => 2,
							'RIGHT_ID' => 3,
							'ITEM_PARENTS' => '',
							'DEPTH' => 1,
							'FULL_URL' => '#',
							'BOARD_URL' => 'http://www.example.com/phpBB',
							'MOD_REWRITE_ENABLED' => '',
							'HOST' => '',
							'URL_PATH' => '',
							'URL_QUERY' => [],
							'IS_NAVIGABLE' => false,
							'IS_EXPANDABLE' => false,
							'PREV_DEPTH' => 0,
							'THIS_DEPTH' => 1,
							'IS_CURRENT' => false,
							'IS_PARENT' => false,
							'NUM_KIDS' => 0,
							'close' => [''],
						),
					),
					'close' => [''],
				),
			),
		);
	}

	/**
	 * Test menu block display
	 *
	 * @dataProvider menu_block_test_data
	 * @param array $page_data
	 * @param array $bdata
	 * @param bool $editing
	 * @param mixed $expected
	 */
	public function test_menu_block_display(array $page_data, array $bdata, $editing, $expected)
	{
		$block = $this->get_block($page_data);
		$result = $block->display($bdata, $editing);

		$this->assertEquals($expected, is_array($expected) ? $result['data'] : $result['content']);
	}
}
