services:
    blitze.sitemaker.cfg_field_collection:
        class: phpbb\di\service_collection
        arguments:
            - '@service_container'
        tags:
            - { name: service_collection, tag: sitemaker.cfg_field }

    blitze.sitemaker.cfg_field.base:
        class: blitze\sitemaker\services\blocks\config\fields\cfg_field_base
        abstract:  true
        arguments:
            - '@language'

    blitze.sitemaker.cfg_field.checkbox:
        class: blitze\sitemaker\services\blocks\config\fields\checkbox
        parent: blitze.sitemaker.cfg_field.base
        tags:
            - { name: sitemaker.cfg_field }

    blitze.sitemaker.cfg_field.code_editor:
        class: blitze\sitemaker\services\blocks\config\fields\code_editor
        parent: blitze.sitemaker.cfg_field.base
        tags:
            - { name: sitemaker.cfg_field }

    blitze.sitemaker.cfg_field.custom:
        class: blitze\sitemaker\services\blocks\config\fields\custom
        parent: blitze.sitemaker.cfg_field.base
        tags:
            - { name: sitemaker.cfg_field }

    blitze.sitemaker.cfg_field.hidden:
        class: blitze\sitemaker\services\blocks\config\fields\hidden
        parent: blitze.sitemaker.cfg_field.base
        tags:
            - { name: sitemaker.cfg_field }

    blitze.sitemaker.cfg_field.multi_input:
        class: blitze\sitemaker\services\blocks\config\fields\multi_input
        parent: blitze.sitemaker.cfg_field.base
        tags:
            - { name: sitemaker.cfg_field }

    blitze.sitemaker.cfg_field.multi_select:
        class: blitze\sitemaker\services\blocks\config\fields\multi_select
        parent: blitze.sitemaker.cfg_field.base
        tags:
            - { name: sitemaker.cfg_field }

    blitze.sitemaker.cfg_field.radio:
        class: blitze\sitemaker\services\blocks\config\fields\radio
        parent: blitze.sitemaker.cfg_field.base
        tags:
            - { name: sitemaker.cfg_field }

    blitze.sitemaker.cfg_field.select:
        class: blitze\sitemaker\services\blocks\config\fields\select
        parent: blitze.sitemaker.cfg_field.base
        tags:
            - { name: sitemaker.cfg_field }
