parameters:
    tables.sitemaker.blocks: '%core.table_prefix%sm_blocks'
    tables.sitemaker.block_routes: '%core.table_prefix%sm_block_routes'
    tables.sitemaker.cblocks: '%core.table_prefix%sm_cblocks'
    tables.sitemaker.menus: '%core.table_prefix%sm_menus'
    tables.sitemaker.menu_items: '%core.table_prefix%sm_menu_items'
    sitemaker.cache_time: 10800
    filemanager.config_path: '%core.root_path%ResponsiveFilemanager/filemanager/config/'
    filemanager.lang_mapping:
        'bg'          : 'bg_BG'
        'de_x_sie'    : 'de'
        'en_us'       : 'en'
        'es_x_tu'     : 'es'
        'fr'          : 'fr_FR'
        'he'          : 'he_IL'
        'hr_x_vi'     : 'hr'
        'hu'          : 'hu_HU'
        'mk'          : 'mk_MK'
        'nb'          : 'nb_NO'
        'nl_x_formal' : 'nl'
        'pt_preao'    : 'pt_PT'
        'sl'          : 'sl_SI'
        'sv'          : 'sv_SE'
        'th'          : 'th_TH'
        'zh_cmn_hans' : 'zh_CN'
        'zh_cmn_hant' : 'zh_TW'
