project_identifier_env: CROWDIN_SITEMAKER_DOCS_PROJECT_ID
api_key_env: CROWDIN_SITEMAKER_DOCS_API_KEY
base_path: "./"
preserve_hierarchy: true
# commit_message: 'New translation for %original_file_name% in %language%'
# append_commit_message: false

files:
  -
    source: '/docs/*.md'
    translation: '/website/translated_docs/%locale%/%original_file_name%'
    languages_mapping: &anchor
      locale:
        'bs-BA': 'bs_ba'
        'es-ES': 'es'
        'pt-BR': 'pt_preao'
        'pt-PT': 'pt'
        'sv-SE': 'sv'
        'zh-CN': 'zh_cmn_hans'
        'zh-TW': 'zh_cmn_hant'
  -
    source: '/website/i18n/en.json'
    translation: '/website/i18n/%locale%.json'
    languages_mapping: *anchor
  -
    source: '/website/versioned_docs/**/*.md'
    translation: '/website/translated_docs/%locale%/**/%original_file_name%'
    languages_mapping: *anchor
